---
title: "Average distances"
format: html
---

```{julia}
#| code-fold: true
#| output: false
# code from prior sections: load packages used here
using CSV, DataFrames, PhyloNetworks, StatsBase
```

For trait evolution, we need a phylogeny with branch lengths.
These lengths will be used to parametrize how much trait evolution
occurred along each branch (up to a factor that will be estimated).
So they need to represent evolutionary time that can reasonably be 
assumed to represent the amount of trait evolution.
Typically, this assumption is reasonable for branch lengths proportional
to calendar time,
or to substitutions/site (amount of molecular evolution).

In this section and next, we show how to "calibrate" a given network
topology, to have branch lengths in substitutions per site.

We want these lengths to represent substitutions/site observed in data,
so this section show how to estimate genetic distances from gene
trees.
These genetic distances are used in the next section to
[calibrate](topic4-netcalibration.qmd#input-genetic-distances)
a network.

Using gene trees from multiple loci may be best when loci are sufficiently
informative. With short loci or with loci with few informative sites,
some branch lengths may often be underestimated at 0 due to a lack of variable
sites, in which case it may be best to estimate genetic distances from the
multiple alignment directly.

If loci are sufficiently informative, estimating a gene tree from each locus
may help reduce noise in the estimated distances (e.g. account for multiple
substitutions along the same lineage). It can also decrease the influence
of fast-evolving genes, and rate variation across genes more generally.

We first load [helper functions](https://github.com/JuliaPhylo/PhyloUtilities/blob/main/scripts/averagetaxondistances.jl)
for computing pairwise distances, to
- get a matrix of pairwise distances from each tree
- normalize these distance matrices, so they all have a similar distance between
  the ingroup and outgroup taxa
- average distance matrices across genes.
These functions were originally developed by [Karimi et al. (2020)](https://doi.org/10.1093/sysbio/syz073).
To load them, do this below within your julia session:
```{julia}
#| output: false
include(download(
  "https://raw.githubusercontent.com/JuliaPhylo/PhyloUtilities/refs/heads/main/scripts/averagetaxondistances.jl"
))
```
(or copy & paste [them](https://github.com/JuliaPhylo/PhyloUtilities/blob/main/scripts/averagetaxondistances.jl))



This tutorial comes with a small sample of gene trees, some of them modified
so as to illustrate the case when taxa are missing from some genes.
These gene tree files are in folder `data/genetrees_sample`, and are
majority-rule consensus trees in nexus format created by MrBayes.
This is only to give example code to read gene tree files and calculate
distances. In practice, the majority-rule creates edges of length 0 (polytomies)
when there is less than 50% credibility for a resolution in the gene tree,
so this is underestimating the true edge length, and a full consensus tree may
be a better option.

Below, we show how to read these files using `readnexus_treeblock` because of the
nexus format. This function is meant to read a sample of multiple trees (or
multiple networks), so it returns a list. We only use the first and only tree
in this list.
As we can see, loci L10 and L20 are missing a few taxa.

```{julia}
genetreefolder = joinpath("data","genetrees_sample")
# list the content of this folder, and filter to keep files ending in ".tre":
genetreefiles = filter(x -> endswith(x,".tre"), readdir(genetreefolder))
length(genetreefiles) # 19 files: L22 missing
function read1gene(filename)
  genetreefile = joinpath(genetreefolder, filename)
  return readnexus_treeblock(genetreefile)[1] # first and only tree in the list
end
genetrees = read1gene.(genetreefiles)
for (filename,tree) in zip(genetreefiles, genetrees)
  println("$filename: $(tree.numtaxa) taxa")
end
```

To convert each tree to a matrix of pairwise distances, we first need to decide
the order in which the taxa should be listed.
```{julia}
taxa_long = sort!(union(tiplabels.(genetrees)...))
D, ngenes, geneind = getpairwisedistances(genetrees, taxa_long);
geneind # indices of genes with some missing taxa
```

```{julia}
ngenes # number of genes with data for each pair: 19 for most, some 17's and 18's
```

```{julia}
D[11] # distance matrix from 11th gene in the list. if missing taxa, then 0s
```

Now we want to rescale each distance matrix so as to limit the impact of rate
variation across genes. Otherwise, fast-evolving genes would overwhelm the
signal, which may be particularly dangerous if these fast-evolving genes
have saturated edge lengths or are affected by long-branch attraction.

For normalizing the median distance between all pairs of ingroup-outgroup taxa,
we define these sets of taxa:
```{julia}
outgroup = filter(x -> occursin("micranthum",x), taxa_long)
ingroup = setdiff(taxa_long, outgroup)
med_in2out = normalizedistances_outgroup2ingroup!(D,
  taxa=taxa_long, ingroup=ingroup, outgroup=outgroup);
med_in2out
```
We can see that all genes had somewhat similar rates, because similar median
ingroup-to-outgroup distances, except for gene 15, that had a particularly smaller
rate than others.
If there is reason to think that slow-evolving genes may need to be removed,
a filtering step could be added at this point.
For the sake of providing example code, we do this here.

```{julia}
slowgene_indices = findall(d -> d < 0.003, med_in2out) # gene 15 here
```

Gene 15 was not missing any taxa: `geneind` did not list that gene.
So we don't have to re-run the calculation of the vector of D matrix
and of the matrix storing the number of genes contributing data for each
pair of taxa. Otherwise, we would need to re-run the calculation of `ngenes`.

```{julia}
deleteat!(D, slowgene_indices); # deletes D[k] for a slow gene k
num_slow = length(slowgene_indices) # 1: number of slow genes that are being exluded
ngenes .-= num_slow # gene 15 was not missing any taxa
length(D) # 18: 1 fewer than before
```

Now we can see how the distance matrix changed for the first gene,
which we looked at earlier:
```{julia}
D[11] # from 11th gene, after normalization. 0s on rows & columns for missing taxa
```

Finally, let's average distances across genes
```{julia}
avD = averagepairwisedistances(D, ngenes)
```

and save this average distance matrix to a file:
```{julia}
csv_filename = joinpath(genetreefolder, "averagedist_sample.csv")
avD_df = DataFrame([avD[:,j] for j in 1:size(avD,2)], # column data
                   [Symbol(t) for t in taxa_long])    # column names
CSV.write(csv_filename, avD_df)
```
